### ISSUE TITLE
dbb-ucd-packaging.groovy is packaging outputs with a deploy type of null when they should be ignored

### ISSUE THREAD

**Issue by peterceck** [IBM/dbb#76] opened 2021-04-26 15:11 UTC
In my testing dbb-ucd-packaging.groovy is packaging outputs with a deploy type of null when they should be ignored.  I believe it is because my DBB output has other members with a valid deploy type so the packaging code is incorrectly treating all members as having a valid deploy type.

**Comment by jbyibm** [comment] 2021-04-26 15:24
There is a case not handled by the script. When in the outputs we have more than one entry. If for example we have 2 entries and one of the 2 entries is not null then the 2 entries will be added.

A temporary workaround is to surround this with this test if ( output.deployType != null):


![image](https://user-images.githubusercontent.com/60784175/116108445-31842500-a6b4-11eb-9371-de4a86e59ff3.png)

**Comment by jbyibm** [comment] 2021-04-26 16:34
@dennis-behm  This fix is in this PR https://github.com/IBM/dbb/pull/75 (with another one).

@peterceck  FYI

**Comment by dennis-behm** [comment] 2021-04-26 18:08
Well, just briefly. 

Why should we not allow an empty deployType? According to the UCD docs, this is optional:
https://www.ibm.com/docs/en/urbancode-deploy/7.1.1?topic=platform-ship-list-files

Peter, what is the issue you are facing? Does the packaging or the deployment fails?

**Comment by peterceck** [comment] 2021-04-26 18:24
Yes, the UCD deployment fails if there is no mapping rule for the object type.  See my UCD output below.  I could deploy the object to a dummy dataset because it is not a executable that needs to be deployed.  But this is wasteful. It is better to exclude it from the package like we always did with RTC.   If a type does need to be deployed then the DBB build scripts can be updated to set a deploy type for it.

 /usr/lpp/java/J8.0_64/bin/java -Djava.library.path=/var/ucd/v7/lib/zos/ -Dfile.encoding=IBM-1047 -Dconsole.encoding=IBM-1047 -Djdk.tls.client.protocols=TLSv1.2 -Xmx128m -cp /var/ucd/v7/opt/apache-ant-1.9.15/lib/ant.jar:/var/ucd/v7/opt/apache-ant-1.9.15/lib/ant-launcher.jar:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/lib/ant-contrib.jar:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/lib/zos-deploy-common.jar:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/lib/uDeployRestClient.jar:/var/ucd/v7/lib/zos/zostoolkit.jar:/var/ucd/v7/opt/zoslib/slpp.jar:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/classes:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/lib/securedata.jar:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/lib/jettison-1.1.jar:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/lib/commons-codec.jar:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/lib/zos-deploy-native.jar:/var/ucd/v7/var/plugins/com.ibm.ucd.plugin.zos_54_2e7ccba3dca88967d25b4c928292464af064f26c4687210cee57ed248c067a1f/lib/CommonsUtil.jar:/var/ucd/v7/opt/groovy-2.4.15/lib/* deploy_package /var/ucd/v7/var/temp/logs3682168535997635658/input.props /var/ucd/v7/var/temp/logs3682168535997635658/output.props
	Missing PDS mapping rules for:  PCECK.TUTO.GITLAB.MORTGAGE.OBJ

**Comment by dennis-behm** [comment] 2021-04-26 18:39
Ok, it fails, because there is no PDS mapping in your case. So, isn't the problem located earlier in the process?

Isn't it an issue on zAppBuild, that it reports `PCECK.TUTO.GITLAB.MORTGAGE.OBJ` as an output, while we don't would like to have it as an output?

**Comment by jbyibm** [comment] 2021-04-26 19:04
@dennis-behm  The current code in  `dbb-ucd-packaging.groovy` filter the cases when the deployType is null but not all cases see; https://github.com/IBM/dbb/issues/76#issuecomment-826927925. I think this case arrived with OBJ and COPYBOOK. Now @drbruce-git may have a good reason to make zAppBuild adding  OBJ and COPYBOOK as outputs.

**Comment by jbyibm** [comment] 2021-04-26 19:10
And this  fix here: https://github.com/jbyibm/dbb/commit/a2ef28f815a5d0b767121e6c3db219ef2a125094

**Comment by drbruce-git** [comment] 2021-04-26 20:06
While it is true that the deployType field requires the output field to be set, the reverse is not true.  You can have an output field without a deploy type.  This was done by design (and is similar to RTC-EE) and allows you to record the fact in your build report that a build step resulted in an output for use by another language build without it necessarily meant to be deployed like an OBJ deck or BMS Copybook

**Comment by dennis-behm** [comment] 2021-06-11 11:06
Closing while it has been resolved

**Closed by dennis-behm** 2021-06-11 11:06 UTC
